version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=SQL_DATABASE
      - POSTGRES_USER=SQL_USER
      - POSTGRES_PASSWORD=SQL_PASSWORD
    ports:
      - "5435:5432"
    restart: "on-failure"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/Home/app/webapp/
    ports:
      - '8000:8000'
    depends_on:
      - db
volumes:
  postgres_data:
